name: nested_navigation
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^2.3.0
  stacked_services: ^0.8.17
  logger: ^1.1.0
  stacked_themes: ^0.3.8+1
  animations: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  stacked_generator: ^0.5.7

flutter:
  uses-material-design: true